import Footer from "@/components/Footer";
import Hedder from "@/components/Hedder";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="   flex flex-col items-center justify-center  ">
        <Hedder />
        <Footer />
      </div>
    </>
  );
}
