import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="   flex flex-col items-center justify-center  ">
        <h1 className="text-2xl font-bold text-amber-600 dark:text-amber-50">hello</h1>
        <ModeToggle/>
      </div>
    </>
  );
}
